accounts/urls.py
# accounts/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('accounts-cart/', views.accounts_cart, name='accounts_cart'),
]

app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='buypage'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('<slug:category_slug>/', views.catalog, name='buypage'),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
    path('qr_code/<int:order_id>/', views.qr_code, name='qr_code'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Account(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    phone_number = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        db_table = "user"
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

orders/models.py
from django.db import models
from accounts.models import Account  # Импортируем модель Account
from goods.models import Products

class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Order(models.Model):
    account = models.ForeignKey(to=Account, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)  # Используем модель Account напрямую
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    # requires_delivery = models.BooleanField(default=False, verbose_name="Требуется доставка")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    # payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при получении")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")
    qr_image = models.ImageField(upload_to='qr_codes/', null=True, blank=True, verbose_name="QR-код")  # Новое поле для QR-кода
    first_name = models.CharField(max_length=150, verbose_name="Имя получателя", blank=True, null=True, default=None)
    last_name = models.CharField(max_length=150, verbose_name="Фамилия получателя", blank=True, null=True, default=None)

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.account.first_name} {self.account.last_name}"  


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from accounts.models import Account

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = Account
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)



class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = Account
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )

    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

class ProfileForm(UserChangeForm):
    class Meta:
        model = Account
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = Account
        fields = (
            "username",
            "email",
            "avatar",
        )

    username = forms.CharField()
    email = forms.EmailField()
    avatar = forms.ImageField(required=False)
    
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

accounts/views.py
from django.contrib.auth import login, authenticate
from django.db.models import F, Prefetch, Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from accounts.forms import UserRegistrationForm, ProfileForm
from django.contrib.auth.decorators import login_required

from orders.models import Order, OrderItem

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('accounts:profile')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = ProfileForm(instance=request.user)

    # Измените фильтрацию заказов
    orders = (
        Order.objects.filter(account=request.user).prefetch_related(
            Prefetch(
                'orderitem_set',
                queryset=OrderItem.objects.select_related('product')
            )
        ).order_by('-id')
    )
    
    for order in orders:
        order.total_price = order.orderitem_set.aggregate(total=Sum(F('price') * F('quantity')))['total']

    context = {
        'form': form,
        'orders': orders,
    }
    return render(request, 'accounts/profile.html', context)


def accounts_cart(request):
    return render(request, 'accounts/accounts_cart.html')

def my_orders(request):

    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('accounts:profile'))
        # else:
        #     # Возвращаем страницу, которая содержит модальное окно, с контекстом, чтобы показать ошибки
        #     context = {
        #         'form': form
        #     }
    else:
        form = ProfileForm(instance=request.user)

    orders = (
            Order.objects.filter(user=request.user).prefetch_related(
                Prefetch(
                    'orderitem_set',
                    queryset=OrderItem.objects.select_related('product')
                )
            ).order_by('-id')
        )
    
    for order in orders:
        order.total_price = order.orderitem_set.aggregate(total=Sum(F('price') * F('quantity')))['total']

    context = {
        "title": "Спорт Лайн - Мои заказы", 
        'form': form,
        'orders': orders,
        }
    return render(request, "accounts/profile.html", context)

accounts/templates/accounts/accounts_cart.html
{% extends "main/base.html" %}
{% load static %}
{% load carts_tags %}
{% block css %}
<link rel="stylesheet" href="{% static "deps/styles/acoounts_cart.css" %}">
{% endblock css %}

{% user_carts request as carts %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "carts/includes/included_cart.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
                <div class="text-center">
                    <a class="btn btn-dark" href="{% url "orders:create_order" %}">
                        Оформить заказ
                    </a>
                </div>
                
            </div>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "main/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "deps/styles/loginpage.css" %}">
{% endblock css %}

{% block content %}
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col lg-5"></div>
            <div class="col-lg-2 col-md-12">
                <div class="row">
                    <div class="imagelogin">
                        <img class="iconlogin" src="{% static 'deps/image/СердечкоДляВхода.png' %}" alt="icon">
                    </div>
                </div>
                <form id="form1" method="post" action="{% url 'accounts:login' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="button">
                        <button type="submit" class="btn btn-light custom-btn">Войти</button>
                    </div>
                </form>
                <p class="reg">Нет аккаунта? <a href="{% url 'accounts:register' %}">Зарегистрироваться</a></p>
            </div>
            <div class="col lg-5"></div>
        </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "main/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'deps/styles/profile.css' %}">
{% endblock css %}
{% load carts_tags %}

{% block content %}
<section>
    <div class="container py-5">
        <p class="yourpassport">МОЙ ПАСПОРТ</p>
        <div class="row d-flex justify-content-center align-items-center">
            <div class="col-md-9 col-lg-7 col-xl-5 custom">
                <div class="card" style="border-radius: 16px; color: black;">
                    <div class="card-body p-4">
                        <div class="text-black d-flex align-items-center">
                            <div class="flex-shrink-0 me-4">
                                {% if user.avatar %}
                                    <img src="{{ user.avatar.url }}" alt="User avatar" class="img-fluid" style="width: 180px; border-radius: 10px;">
                                {% else %}
                                    <img src="{% static 'deps/image/СердечкоДляВхода.png' %}" alt="Generic placeholder image" class="img-fluid" style="width: 180px; border-radius: 10px;">
                                {% endif %}
                            </div>
                            <div class="flex-grow-1">
                                <div class="d-flex justify-content-start rounded-3 p-2 mb-2" style="background-color: #efefef;">
                                    <div>
                                        <h5><strong>Мои данные:</strong></h5>
                                        <h5 class="mb-1">{{ user.username }}</h5>
                                        <h5 class="mb-1">{{ user.email }}</h5>
                                    </div>
                                </div>
                                <a class="btn btn-light custom-btn mb-2" href="{% url 'accounts:logout' %}">Выйти</a>
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <button type="submit" class="btn btn-light custom-btn">Сохранить изменения</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Мои заказы</h3>
                    {% if orders %}
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            {% for order in orders %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        Заказ № {{ order.id }} - {{ order.created_timestamp }} | Статус: <strong class="mx-2">{{ order.status }}</strong>
                                    </button>
                                </h2>
                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-hover table-striped">
                                            <thead class="table-light">
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-dark" href="{% url 'goods:product' item.product.slug %}">{{ item.product.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% else %}
                    <h5 class="text-center">Ты ещё ничего не заказал( •̀ .̫ •́ )✧</h5>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "main/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "deps/styles/regpage.css" %}">
{% endblock css %}

{% block content %}
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col lg-5"></div>
            <div class="col-lg-2 col-md-12">
                <div class="row">
                    <div class="imagereg">
                        <img class="iconreg" src="{% static "deps/image/СтрелкаДляРегистрации.png" %}" alt="icon">
                    </div>
                </div>
                <form method="post" action="{% url 'accounts:register' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="button">
                        <button type="submit" class="btn btn-light custom-btn">Зарегистрироваться</button>
                    </div>
                </form>
                <p class="log">Уже есть аккаунт? <a href="{% url 'accounts:login' %}">Войти</a></p>
            </div>
            <div class="col lg-5"></div>
        </div>
    </div>
</section>
{% endblock content %}