app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
# carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/<slug:product_slug>/', views.cart_add, name='cart_add'),
    path('cart_change/<int:cart_id>/', views.cart_change, name='cart_change'),
    path('cart_remove/<int:cart_id>/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='buypage'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('<slug:category_slug>/', views.catalog, name='buypage'),
]

goods/models.py
# models.py
from django.db import models

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Главное изображение')
    image2 = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение 2')
    image3 = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение 3')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ("id", )

    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'
    
    def display_id(self):
        return f"{self.id:05}"
    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price

goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
from goods.models import Products

def catalog(request, category_slug=None):
    page = request.GET.get('page', 1)

    if category_slug == 'all' or category_slug is None:
        goods = Products.objects.all()
    elif category_slug == 'kolechki':
        goods = Products.objects.filter(category__slug=category_slug)
    elif category_slug == 'seryozhki':
        goods = Products.objects.filter(category__slug=category_slug)
    elif category_slug == 'drugoe':
        goods = Products.objects.filter(category__slug=category_slug)
    else:
        goods = Products.objects.filter(category__slug=category_slug)

    paginator = Paginator(goods, 6)
    current_page = paginator.get_page(page)

    context = {
        "title": "Украшения Мари - Каталог",
        "goods": current_page,
        "category_slug": category_slug,
        "paginator": paginator,
        "page_obj": current_page
    }
    return render(request, "goods/catalog.html", context)

def product(request, product_slug):
    product = get_object_or_404(Products, slug=product_slug)

    context = {
        'product': product
    }

    return render(request, "goods/product.html", context=context)

goods/templates/goods/catalog.html
{% extends "main/base.html" %}
{% load static %}
{% load goods_tags %}

{% block section %}
<section>
    <div class="container-fluid mt-4">
        <div class="row px-2">
            <div class="col-lg-3 col-md-12">
                <div class="row">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                    <div class="col-lg-12 sidebar slidecustom1 my-4">
                        <a href="{% url 'goods:buypage' category.slug %}" class="{% if category.slug == category_slug %}current-category{% else %}other-category{% endif %}">
                            {{ category.name }}
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="col-lg-8 col-md-12">
                <div class="row">
                    {% for product in goods %}
                    <div class="col-lg-4 col-md-6 mt-4">
                        <div class="card">
                            {% if product.image %}
                                <a href="{% url 'goods:product' product.slug %}"><img src="{{ product.image.url }}" class="card-img-top" alt="card"></a>
                            {% else %}
                                <a href="{% url 'goods:product' product.slug %}"><img src="{% static 'deps/image/кольцочёрное.png' %}" class="card-img-top" alt="card"></a>
                            {% endif %}
                            <div class="card-body">
                                <h4 class="card-title"><a href="{% url 'goods:product' product.slug %}">{{ product.name }}</a></h4>
                                {% if product.discount %}
                                    <p><strong><s>{{ product.price }}</s>$</strong></p>
                                    <p><strong>{{ product.sell_price }}$</strong></p>
                                    <span class='badge bh-bg-warning text-dark'>Скидка {{ product.discount }}%</span>
                                {% else %}
                                    <p><strong>{{ product.price }}</strong></p>
                                {% endif %}

                                <a href="{% url "cart:cart_add" product.slug %}" class="btn btn-light custom-btn">В корзину</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="switchingnumbers">
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            {% if goods.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ goods.previous_page_number }}{% if category_slug %}&category={{ category_slug }}{% endif %}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                            {% for num in goods.paginator.page_range %}
                                {% if goods.number == num %}
                                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                                {% elif num > goods.number|add:'-3' and num < goods.number|add:'3' %}
                                    <li class="page-item"><a class="page-link" href="?page={{ num }}{% if category_slug %}&category={{ category_slug }}{% endif %}">{{ num }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if goods.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ goods.next_page_number }}{% if category_slug %}&category={{ category_slug }}{% endif %}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>                
            </div>
            <div class="col-lg-1">
            </div>
        </div>
    </div>
</section>
{% endblock section %}

goods/templates/goods/kolechki.html
{% extends "main/base.html" %}
{% load static %}
{% load goods_tags %}

{% block section %}
<section>
    <div class="container-fluid mt-4">
        <div class="row px-2">
            <div class="col-lg-3 col-md-12">
                <div class="row">
                    <div class="col-lg-12 sidebar slidecustom1 my-4">
                        {% tag_categories as categories %}
                        {% for category in catalog %}
                        <li class="nav-item">
                            <a class="nav-link p-0 pt-2" href="{% url "catalog:buypage" category.slug %}">{{ category.name }}</a>
                        </li>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="col-lg-8 col-md-12">
                <div class="row">
                    {% for product in kolechki %}
                    <div class="col-lg-4 col-md-6 mt-4">
                        <div class="card">
                            {% if product.image %}
                                <a href="{% url "catalog:product" product.slug %}"><img src="{{ product.image.url }}" class="card-img-top" alt="card"></a>
                            {% else %}
                                <a href="{{ product.url }}"><img src="{% static "deps/image/кольцочёрное.png" %}" class="card-img-top" alt="card"></a>
                            {% endif %}
                            <div class="card-body">
                                <h4 class="card-title"><a href="{% url "catalog:product" product.slug %}">{{ product.name }}</a></h4>
                                <p class="product_id">id: {{ product.display_id }}</p>
                                {% if product.discount %}
                                    <p><strong><s>{{ product.price }}</s>$</strong></p>
                                    <p><strong>{{ product.sell_price }}$</strong></p>
                                    <span class='badge bh-bg-warning text-dark'>Скидка {{ product.discount }}%</span>
                                {% else %}
                                    <p><strong>{{ product.price }}</strong></p>
                                {% endif %}

                                <a href="cart.html" class="btn btn-light custom-btn">В корзину</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="switchingnumbers">
                    <p class="switchingnumbers"> <span class="number">1</span> <a href="buypage2.html"><span
                                class="number">2</span></a> <a href=""><span class="number"></span></a></p>
                </div>
            </div>
            <div class="col-lg-1">
            </div>
        </div>
    </div>
</section>
{% endblock section %}

goods/templates/goods/product.html
{% extends "main/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "deps/styles/pagegood.css" %}">
{% endblock css %}

{% block section %}
<section>
    <div class="container-fluid mt-4">
        <div class="row px-2">
            <div class="container-fluid mt-4">
                <div class="row px-2">
                    <div class="col">
                        <div class="row">
                            {% if product.image2 %}
                            <div class="img">
                                <img class="img" src="{{ product.image2.url }}" alt="">
                            </div>
                            <p class="descriptionimg">(рис 1.)</p>
                            {% endif %}
                            {% if product.image3 %}
                            <div class="img">
                                <img class="img" src="{{ product.image3.url }}" alt="">
                            </div>
                            <p class="descriptionimg">(рис 2.)</p>
                            {% endif %}
                        </div>
                    </div>

                    <div class="col-lg-12">
                        <div class="row">
                            <p class="descriptiongood"> {{ product.description }}</p>
                            <div style="margin-top: -35px;">
                                <a href="{% url "cart:cart_add" product.slug %}"><p class="descriptiongood">В корзину</p></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock section %}