accounts/urls.py
# accounts/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('accounts-cart/', views.accounts_cart, name='accounts_cart'),
]

app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
# carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/<slug:product_slug>/', views.cart_add, name='cart_add'),
    path('cart_change/<int:cart_id>/', views.cart_change, name='cart_change'),
    path('cart_remove/<int:cart_id>/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='buypage'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('<slug:category_slug>/', views.catalog, name='buypage'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.buypage, name='buypage'),
    path('category/<slug:category_slug>/', views.buypage, name='category'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('about/', views.about, name='about'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
from goods.models import Categories, Products

def buypage(request, category_slug=None):
    categories = Categories.objects.all()
    page = request.GET.get('page', 1)

    if category_slug and category_slug != 'all':
        products = Products.objects.filter(category__slug=category_slug)
    else:
        products = Products.objects.all()

    paginator = Paginator(products, 6)
    current_page = paginator.get_page(page)

    context = {
        "categories": categories,
        "goods": current_page,
        "category_slug": category_slug,
        "paginator": paginator,
        "page_obj": current_page
    }
    return render(request, "main/buypage.html", context)

def about(request):
    context = {
        'title': 'О нас',
        'content': "О нас",
        'textonpage': "СЛОВО СЛОВО СЛОВО",
    }
    return render(request, 'main/about.html', context)

def product(request, product_slug):
    product = get_object_or_404(Products, slug=product_slug)
    context = {
        'product': product
    }
    return render(request, "goods/product.html", context=context)

main/templates/main/about.html
{% extends "main/base.html" %}
{%load static %}
{% block css %}
<link rel="stylesheet" href="{% static "deps/styles/about.css" %}">
{% endblock css %}

{% block content %}
<section>

    <div class="container-fluid mt-4 customabout">
        <div class="row">
            <div class="col-lg-7 xxl-7 xl-7 ">
                <div class="textabout">
                    <h1>Привет! Меня зовут Мари, и я делаю украшения из полимерной глины &#128578;</h1>
                    <div class="pabout">
                        <p>
                            Я люблю лепить из глины, делать всякие украшения подвесочки, сережечки, бусины, чокеры.
                        </p>
                        <p>
                            Когда я приступаю к созданию нового украшения, я всегда начинаю с мысли о том, как можно
                            сделать его милым, стараюсь вкладывать в него свои чувства. Я выбираю нежные цвета и простые
                            формы.
                            Не могу сказать, что мое творчество какое-то уникальное. Это просто украшения, сделанные с
                            душой, с любовью к еде, природе, но они не несут особую смысловую нагрузку.
                        </p>
                        <p>
                            <a href="https://t.me/Semphora" target="_blank">
                                <img src="{% static "deps/image/telegramicon.png" %}" alt="Telegram Icon"/>
                            </a>
                            — По всем дополнительным вопросам писать сюда!
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 xxl-5 xl-5  textaboutmari">
                <img src="{% static "deps/image/photoMari.jpeg" %} " alt="">
            </div>
        </div>
    </div>
    </div>
{% endblock content %}

main/templates/main/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'deps/styles/buypage.css' %}">
    <link rel="icon" href="{% static 'deps/image/icon.png' %}">
    <title>{{ title }}</title>
    {% block css %}
    {% endblock %}
</head>

<body>

<header>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid" style="background-color: #ffffff;">
            <a href="{% url 'main:buypage' %}"><img class="logomari" src="{% static 'deps/image/logoblacksmall.svg' %}" alt="logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link custom1" aria-current="page" href="{% url 'main:about' %}">О нас</a>
                    <a class="nav-link custom2" href="{% url 'catalog:buypage' %}">Магазин</a>
                    {% if user.is_authenticated %}
                        <a class="nav-link custom3" href="{% url 'accounts:profile' %}">Профиль</a>
                    {% else %}
                        <a class="nav-link custom4" href="{% url 'accounts:login' %}">Войти</a>
                    {% endif %}
                    <a class="nav-link custom5" href="{% url 'accounts:accounts_cart' %}"><button type="button" class="btn btn-light custom-btn1">Корзина</button></a>
                </div>
            </div>
        </div>
    </nav>
</header>

{% block content %}
{% endblock %}

{% block section %}
{% endblock section %}

<footer>
    <div class="copyright">Copyright 2024 Émile Alexanyan</div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/buypage.html
{% extends "main/base.html" %}
{% load static %}
{% load goods_tags %}

{% block section %}
<section>
    <div class="container-fluid mt-4">
        <div class="row px-2">
            <div class="col-lg-3 col-md-12">
                <div class="row">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                    <div class="col-lg-12 sidebar slidecustom1 my-4">
                        <a href="{% url 'goods:buypage' category.slug %}" class="{% if category.slug == category_slug %}current-category{% else %}other-category{% endif %}">
                            {{ category.name }}
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="col-lg-8 col-md-12">
                <div class="row">
                    {% for product in goods %}
                    <div class="col-lg-4 col-md-6 mt-4">
                        <div class="card">
                            {% if product.image %}
                                <a href="{% url 'goods:product' product.slug %}"><img src="{{ product.image.url }}" class="card-img-top" alt="card"></a>
                            {% else %}
                                <a href="{% url 'goods:product' product.slug %}"><img src="{% static 'deps/image/кольцочёрное.png' %}" class="card-img-top" alt="card"></a>
                            {% endif %}
                            <div class="card-body">
                                <h4 class="card-title"><a href="{% url 'goods:product' product.slug %}">{{ product.name }}</a></h4>
                                {% if product.discount %}
                                    <p><strong><s>{{ product.price }}</s>$</strong></p>
                                    <p><strong>{{ product.sell_price }}$</strong></p>
                                    <span class='badge bh-bg-warning text-dark'>Скидка {{ product.discount }}%</span>
                                {% else %}
                                    <p><strong>{{ product.price }}</strong></p>
                                {% endif %}

                                <a href="{% url "cart:cart_add" product.slug %}" class="btn btn-light custom-btn">В корзину</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="switchingnumbers">
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            {% if goods.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ goods.previous_page_number }}{% if category_slug %}&category={{ category_slug }}{% endif %}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                            {% for num in goods.paginator.page_range %}
                                {% if goods.number == num %}
                                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                                {% elif num > goods.number|add:'-3' and num < goods.number|add:'3' %}
                                    <li class="page-item"><a class="page-link" href="?page={{ num }}{% if category_slug %}&category={{ category_slug }}{% endif %}">{{ num }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if goods.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ goods.next_page_number }}{% if category_slug %}&category={{ category_slug }}{% endif %}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>                
            </div>
            <div class="col-lg-1">
            </div>
        </div>
    </div>
</section>
{% endblock section %}